ccflags-y := 	-Wall					\
		-Wextra					\
		-Wno-missing-field-initializers		\
		-Wno-unused-parameter			\
		-Wformat				\
		-std=gnu18				\
		-g					\
		-Werror=format-security			\
		-Werror=implicit-function-declaration   \

obj-m := lsbdd.o
lsbdd-objs := main.o utils/btree-utils.o utils/skiplist.o utils/ds-control.o utils/hashtable-utils.o utils/rbtree.o
