ccflags-y := 	-Wall					\
		-Wextra					\
		-Wno-missing-field-initializers		\
		-Wno-unused-parameter			\
		-Wformat				\
		-std=gnu18				\
		-g					\
		-Werror=format-security			\
		-Werror=implicit-function-declaration	

obj-m := lsbdd.o
bdrm-objs := main.o include/btreeutils.o include/skiplist.o include/dsutils.o include/hashtableutils.o
